### ISSUE TITLE
1

### ISSUE THREAD

**Issue by yc957** [ccj-007/lowcode-editor-send#2]
能问下remark为什么会重复吗

**Comment by ccj-007** [comment]
你可以搜下amis的官方的issue， 命名问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月7日(星期三) 下午3:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [ccj-007/lowcode-editor-send] 1 (Issue #2)





 
能问下remark为什么会重复吗
